services:
  grpc-server:
    build: ./grpc-server
    image: grpc-server:latest
    container_name: grpc_server
    ports:
      - "50051:50051"
    network_mode: "host"
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: psql
      DB_NAME: mydb

  app:
    build: ./app
    container_name: express_opti_app
    ports:
      - "3020:3020"
    network_mode: "host"
    environment:
      PORT: 3020
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: psql
      DB_NAME: mydb

  worker-post:
    build: ./app
    container_name: worker_post
    command: node src/worker/checkoutPost.worker.js

  worker-edit:
    build: ./app
    container_name: worker_edit
    command: node src/worker/checkoutEdit.worker.js
  

  worker-patch:
    build: ./app
    container_name: worker_patch
    command: node src/worker/checkoutPatch.worker.js
