services:
  app:
    build: ./app
    container_name: express_opti_app
    ports:
      - "3020:3020"
    environment:
      PORT: 3000
      DB_HOST: host.docker.internal
      DB_USER: postgres
      DB_PASSWORD: psql
      DB_NAME: mydb
    networks:
      - monitoring

 
networks:
  monitoring:
    external: true
