services:
  app:
    build: ./app
    container_name: express_opti_app
    ports:
      - "3020:3020"
    environment:
      PORT: 3020
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: psql
      DB_NAME: mydb
